serviceMaps:
  serviceName: bpa-services
  mappings:

    - version: 1.0
      description: Creates BPA application in eg_bpa_buildingplans
      fromTopic: save-bpa-buildingplan
      isTransaction: true
      queryMaps:

        # Insert main building plan data
        - query: >
            INSERT INTO public.ug_bpa_buildingplans
            (id, application_no, tenant_id, edcr_number, status, application_date,
             approval_no, approval_date, business_service, account_id, application_type,
             risk_type, land_id, created_by, created_time, last_modified_by, last_modified_time, additional_details)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?::JSONB);
          basePath: BPA
          jsonMaps:
            - jsonPath: $.BPA.id
            - jsonPath: $.BPA.applicationNo
            - jsonPath: $.BPA.tenantId
            - jsonPath: $.BPA.edcrNumber
            - jsonPath: $.BPA.status
            - jsonPath: $.BPA.applicationDate
            - jsonPath: $.BPA.approvalNo
            - jsonPath: $.BPA.approvalDate
            - jsonPath: $.BPA.businessService
            - jsonPath: $.BPA.accountId
            - jsonPath: $.BPA.applicationType
            - jsonPath: $.BPA.riskType
            - jsonPath: $.BPA.landId
            - jsonPath: $.BPA.auditDetails.createdBy
            - jsonPath: $.BPA.auditDetails.createdTime
            - jsonPath: $.BPA.auditDetails.lastModifiedBy
            - jsonPath: $.BPA.auditDetails.lastModifiedTime
            - jsonPath: $.BPA.additionalDetails
              type: JSON
              dbType: JSONB

        # Insert documents associated with BPA
        - query: >
            INSERT INTO public.ug_bpa_documents
            (id, document_type, filestore_id, document_uid, buildingplan_id,
             created_by, created_time, last_modified_by, last_modified_time, additional_details)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?::JSONB);
          basePath: BPA.documents.*
          jsonMaps:
            - jsonPath: $.BPA.documents.*.id
            - jsonPath: $.BPA.documents.*.documentType
            - jsonPath: $.BPA.documents.*.fileStoreId
            - jsonPath: $.BPA.documents.*.documentUid
            - jsonPath: $.BPA.id
            - jsonPath: $.BPA.auditDetails.createdBy
            - jsonPath: $.BPA.auditDetails.createdTime
            - jsonPath: $.BPA.auditDetails.lastModifiedBy
            - jsonPath: $.BPA.auditDetails.lastModifiedTime
            - jsonPath: $.BPA.documents.*.additionalDetails
              type: JSON
              dbType: JSONB

        # Insert RTP allocation details
        - query: >
            INSERT INTO public.ug_bpa_rtp_detail
            (id, buildingplan_id, rtp_category, rtp_id, rtp_name,
             assignment_status, assignment_date, changed_date, remarks,
             created_by, created_time, last_modified_by, last_modified_time, additional_details)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?::JSONB);
          basePath: BPA.rtpDetails
          jsonMaps:
            - jsonPath: $.BPA.rtpDetails.id
            - jsonPath: $.BPA.id
            - jsonPath: $.BPA.rtpDetails.rtpCategory
            - jsonPath: $.BPA.rtpDetails.rtpUUID
            - jsonPath: $.BPA.rtpDetails.rtpName
            - jsonPath: $.BPA.rtpDetails.assignmentStatus
            - jsonPath: $.BPA.rtpDetails.assignmentDate
            - jsonPath: $.BPA.rtpDetails.changedDate
            - jsonPath: $.BPA.rtpDetails.remarks
            - jsonPath: $.BPA.auditDetails.createdBy
            - jsonPath: $.BPA.auditDetails.createdTime
            - jsonPath: $.BPA.auditDetails.lastModifiedBy
            - jsonPath: $.BPA.auditDetails.lastModifiedTime
            - jsonPath: $.BPA.rtpDetails.additionalDetails
              type: JSON
              dbType: JSONB

        # Insert Area Mapping details (new addition)
        - query: >
            INSERT INTO public.ug_bpa_area_mapping_detail
            (id, buildingplan_id, district, planning_area, planning_permit_authority,
             building_permit_authority, revenue_village, mouza, ward,
             created_by, last_modified_by, created_time, last_modified_time)
            VALUES (?, ?, ?, ?, ?::planning_permit_authority_enum, ?::building_permit_authority_enum, ?, ?, ?, ?, ?, ?, ?);
          basePath: BPA.areaMapping
          jsonMaps:
            - jsonPath: $.BPA.areaMapping.id
            - jsonPath: $.BPA.id
            - jsonPath: $.BPA.areaMapping.district
            - jsonPath: $.BPA.areaMapping.planningArea
            - jsonPath: $.BPA.areaMapping.planningPermitAuthority
            - jsonPath: $.BPA.areaMapping.buildingPermitAuthority
            - jsonPath: $.BPA.areaMapping.revenueVillage
            - jsonPath: $.BPA.areaMapping.mouza
            - jsonPath: $.BPA.areaMapping.ward
            - jsonPath: $.BPA.auditDetails.createdBy
            - jsonPath: $.BPA.auditDetails.lastModifiedBy
            - jsonPath: $.BPA.auditDetails.createdTime
            - jsonPath: $.BPA.auditDetails.lastModifiedTime

    - version: 1.0
      description: Updates BPA application and maintains audit trail
      fromTopic: update-bpa-buildingplan
      isTransaction: true
      queryMaps:

        - query: >
            UPDATE public.ug_bpa_buildingplans
            SET status = ?, approval_no = ?, approval_date = ?, risk_type = ?,
                last_modified_by = ?, last_modified_time = ?, additional_details = ?::JSONB
            WHERE id = ?;
          basePath: BPA
          jsonMaps:
            - jsonPath: $.BPA.status
            - jsonPath: $.BPA.approvalNo
            - jsonPath: $.BPA.approvalDate
            - jsonPath: $.BPA.riskType
            - jsonPath: $.BPA.auditDetails.lastModifiedBy
            - jsonPath: $.BPA.auditDetails.lastModifiedTime
            - jsonPath: $.BPA.additionalDetails
              type: JSON
              dbType: JSONB
            - jsonPath: $.BPA.id

        - query: INSERT INTO public.ug_bpa_buildingplans_audit SELECT * FROM ug_bpa_buildingplans WHERE id = ?;
          basePath: BPA
          jsonMaps:
            - jsonPath: $.BPA.id

        - query: INSERT INTO public.ug_bpa_documents_audit SELECT * FROM ug_bpa_documents WHERE id = ?;
          basePath: BPA.documents.*
          jsonMaps:
            - jsonPath: $.BPA.documents.*.id

        - query: INSERT INTO public.ug_bpa_rtp_detail_audit SELECT * FROM public.ug_bpa_rtp_detail WHERE id = ?;
          basePath: BPA.rtpDetails
          jsonMaps:
            - jsonPath: $.BPA.rtpDetails.id
